name: release

on:
  push:
    branches:
      - main

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: x86_64-pc-windows-gnu, x86_64-pc-windows-msvc, i686-pc-windows-msvc

      - name: Build
        run: |
          cargo build --target x86_64-pc-windows-gnu --release && mv ./target/x86_64-pc-windows-gnu/release/severo-lsp.exe ./target/x86_64-pc-windows-gnu/release/severo-lang-windows.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: interpreter/rust-version/target/x86_64-pc-windows-gnu/release/severo-lang-windows.exe